FROM python:3.10


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir \
    --upgrade -r /code/requirements.txt


COPY ./app /code/app


CMD ["fastapi", "run", "app/main.py", "--port", "80"]

CMD ["gunicorn",\
    "app.main:app",\ 
    "--bind", "0.0.0.0:80",\
    "--workers", "4",\
    "--worker-class",\
    "uvicorn.workers.UvicornWorker",\
    "--log-level", "debug"]